version: "3.0"
services:

  master:
    image: patroni
    container_name: master  
    restart: always
    networks:
      - patroni-net
    environment:
      - POSTGRES_PASSWORD=postgres
      - PATRONI_RESTAPI_CONNECT_ADDRESS=master:8008
      - PATRONI_POSTGRESQL_CONNECT_ADDRESS=master:5432
      - PATRONI_NAME=postgres1

  agent1:
    container_name: agent1
    image: patroni
    restart: always
    networks:
      - patroni-net
    environment:
      - POSTGRES_PASSWORD=postgres
      - PATRONI_RESTAPI_CONNECT_ADDRESS=agent1:8008
      - PATRONI_POSTGRESQL_CONNECT_ADDRESS=agent1:5432
      - PATRONI_NAME=postgres2

  agent2:
    container_name: agent2
    image: patroni
    restart: always
    networks:
      - patroni-net
    environment:
      - POSTGRES_PASSWORD=postgres
      - PATRONI_RESTAPI_CONNECT_ADDRESS=agent2:8008
      - PATRONI_POSTGRESQL_CONNECT_ADDRESS=agent2
      - PATRONI_NAME=postgres3

  etcd:
    image: quay.io/coreos/etcd
    container_name: etcd
    environment:
      - ETCD_NAME=etcd
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd:2380
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_INITIAL_CLUSTER=etcd=http://etcd:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
      - ENABLE-V2=true
    networks:
      - patroni-net

  test-patroni:
    container_name: test-patroni
    image: postgres:13
    restart: always
    networks:
      - patroni-net
    environment:
      - POSTGRES_PASSWORD=postgres

networks:
  patroni-net:

